import "./globals.css";
import NavMenu from "@/components/Header/NavMenu";
import Footer from "@/components/Footer/Footer";



export const metadata = {
  title: "Blackstone The Shilajite",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavMenu/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
